fix
mate-academy/react_people-table-basics pull request #1166
Opened 2023-12-05 17:58 UTC by MaksymKos

https://maksymkos.github.io/react_people-table-basics/

2023-12-05 19:19 UTC, VitaliyBodnar requested changes

2023-12-05 19:19 UTC, VitaliyBodnar commented on src/components/PeoplePage.tsx
> +            : ''}
```suggestion
          {noData && (
              <p data-cy="noPeopleMessage">
                There are no people on the server
              </p>
            )};
```

2023-12-05 19:19 UTC, VitaliyBodnar commented on src/components/PeoplePage.tsx
> +              {people ? <PeopleTable people={people} /> : ''}
```suggestion
              {people && <PeopleTable people={people} /> }
```

2023-12-05 19:19 UTC, VitaliyBodnar commented on src/components/PeopleTable.tsx
> +        }
please don't call a function from the template because it will be executed every time when the state change, so make sense to move it to the variable

2023-12-06 09:46 UTC, etojeDenys requested changes

2023-12-06 09:46 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +        setIsLoadig(true);
looks broken, you must set isLoading true before the request and set false in finally block

2023-12-06 09:46 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +  const [isLoading, setIsLoadig] = useState(false);
```suggestion
  const [isLoading, setIsLoadig] = useState(true);
```
to avoid blinking when peoplePage loading

2023-12-06 11:01 UTC, lerastarynets approved these changes
Great job overall! Left one tiny suggestion for the improvement

2023-12-06 11:01 UTC, lerastarynets commented on src/components/PeopleTable.tsx
> +        })}
```suggestion
      <tbody>
        {people.map(person => (
            <Person person={person} key={person.slug} />
          );
        )}
```

2024-10-14 06:11 UTC, closed without merging