stage-1
mate-academy/react_people-table-basics pull request #1168
Opened 2023-12-06 08:15 UTC by no4kar

[DEMO LINK](https://no4kar.github.io/react_people-table-basics/)

2023-12-06 09:17 UTC, etojeDenys requested changes
try to fix it

2023-12-06 09:17 UTC, etojeDenys commented on src/pages/PeoplePage.tsx
> +          // eslint-disable-next-line
why do you need to disable it

2023-12-06 09:17 UTC, etojeDenys commented on src/pages/PeoplePage.tsx
> +          // eslint-disable-next-line
looks like you forgot to update the todo type

2023-12-07 09:59 UTC, anastasiia-tilikina requested changes
still not working(

try to find another approach

![image](https://github.com/mate-academy/react_people-table-basics/assets/108538921/35b9d423-ada3-4b67-8ee3-0149f6e2e0f9)

2023-12-08 10:40 UTC, etojeDenys approved these changes
good job

2025-04-22 16:42 UTC, closed without merging