solution
mate-academy/react_people-table-basics pull request #1236
Opened 2024-01-14 10:15 UTC by Timi2424

[DEMO LINK](https://Timi2424.github.io/react_people-table-basics/)

2024-01-14 20:05 UTC, mosowiecka approved these changes

2024-01-15 09:25 UTC, mbruhler requested changes
Hi,
Changes are needed.
1. Fix linting issues Error:   1:28  error  Missing file extension for "./types/PersonType"  import/extensions

2. Your app has jumping artifact when routing from home to people tab like in the video. Please fix this

https://github.com/mate-academy/react_people-table-basics/assets/21124163/14ab4e3f-e8b3-4ea6-91bc-4ded4bf2f893

2024-01-15 11:37 UTC, mpiskadlo requested changes
This behavior from Michał's video is still there.
'There are no people on the server' is visible for a fraction of a second when quickly switching from Home to People

2024-01-15 13:12 UTC, danon321 approved these changes

2024-07-05 16:34 UTC, closed without merging