add people from data
mate-academy/react_people-table-basics pull request #128
Opened 2022-04-18 12:57 UTC by AnnSerdechna

[Demo](https://annserdechna.github.io/react_people-table-basics/)

2022-04-18 15:43 UTC, mariiishka requested changes
create a separate folder for each component

2022-04-18 15:43 UTC, mariiishka commented on src/index.tsx
> +  <BrowserRouter>
change to HashRouter

2022-04-18 15:43 UTC, mariiishka commented on src/components/PeoplePage.tsx
> +export const PeoplePage: FC = () => {
Wrap components with React.memo

2022-04-18 15:43 UTC, mariiishka commented on src/components/PeoplePage.tsx
> +export const PeoplePage: FC = () => {
Wrap components with React.memo

2022-04-18 15:43 UTC, mariiishka commented on src/components/PeopleTable.tsx
> +        </tr>
create a PersonRow component
![Снимок](https://user-images.githubusercontent.com/79147126/163833430-32e505bd-70a2-4c98-90af-3ca3427fa825.PNG)

2022-04-18 15:43 UTC, mariiishka commented on src/components/PeopleTable.tsx
> +        </tr>
create a PersonRow component
![Снимок](https://user-images.githubusercontent.com/79147126/163833430-32e505bd-70a2-4c98-90af-3ca3427fa825.PNG)

2022-04-19 09:43 UTC, Ihor-Karpyn approved these changes

2024-12-05 14:39 UTC, closed without merging