task done
mate-academy/react_people-table-basics pull request #1284
Opened 2024-02-12 20:38 UTC by Manankin

[DEMO LINK](https://<your_account>.github.io/react_people-table-basics/)

2024-02-12 21:48 UTC, VasiliyYarosh reviewed
Good Job. Have some advice for u. Fix the demo link. Delete comments which are not necessary. 
![image](https://github.com/mate-academy/react_people-table-basics/assets/91889088/3e0f8e04-cc19-424e-b811-059cdedf885c)

2024-02-13 01:36 UTC, MaxKalalashnyk02 approved these changes
Good work!

2024-02-14 10:10 UTC, DanilWeda requested changes
Good job! 
Please, redeploy the app.
The demo does not work. 
Thanks!

2024-02-14 10:10 UTC, DanilWeda commented on src/PeopleContext.tsx
> +type ContextProps = {
use interface prefer. 
Types have unique features but the interface is best for scaling.

2024-02-14 10:10 UTC, DanilWeda commented on src/PeopleContext.tsx
> +type Props = {
use interface prefer. 
Types have unique features but the interface is best for scaling.

2024-02-14 10:10 UTC, DanilWeda commented on src/pages/People.tsx
> +  }, []);
you can disabled eslint rule  in this case

2024-02-14 10:10 UTC, DanilWeda commented on src/components/personLink/PersonLink.tsx
> +type Props = {
use interface prefer. 
Types have unique features but the interface is best for scaling.

2024-02-14 10:10 UTC, DanilWeda commented on src/components/personLink/PersonLink.tsx
> +  // const selectedPerson = person.slug === slug;
remove commented

2024-02-15 08:19 UTC, olya-shyian requested changes
Great!👍

2024-02-15 08:19 UTC, olya-shyian commented on src/components/peopleTable/PeopleTable.tsx
> +        {/* <tr data-cy="person">
please remove commented code

2024-02-15 08:19 UTC, olya-shyian commented on src/pages/People.tsx
> +        </div>
empty line

2024-02-15 08:19 UTC, olya-shyian commented on src/Root.tsx
> +  return (
in such case please return jsx without using word `return`, in round brackets

2024-02-15 08:19 UTC, olya-shyian commented on src/App.tsx
>      </nav>
it would be great to create a component for navigation

2024-02-15 09:55 UTC, olya-shyian approved these changes
Thank you for the updates!☘️

2024-09-19 12:31 UTC, closed without merging