add solution
mate-academy/react_people-table-basics pull request #134
Opened 2022-04-28 15:40 UTC by romafanasiev

2022-04-29 17:16 UTC, marina-tilniak requested changes

2022-04-29 17:16 UTC, marina-tilniak commented on src/App.tsx
> +      return updatedPerson;
```suggestion
      return {
        ...person,
        mother,
        father,
      };
```

2022-04-29 17:16 UTC, marina-tilniak commented on src/App.tsx
> +    const updatedPersons = persons.map((person) => {
```suggestion
    return persons.map((person) => {
```

2022-04-29 17:16 UTC, marina-tilniak commented on src/App.tsx
> +    return updatedPersons;
delete it

2022-04-29 17:16 UTC, marina-tilniak commented on src/App.tsx
> +          {/* <Route path="/people" element={<p>People page</p>} /> */}
delete commented code

2022-04-29 17:16 UTC, marina-tilniak commented on src/components/PersonRow/PersonRow.tsx
> +      key={slug}
do you need key here?

2022-05-03 12:58 UTC, aliceblunt8 approved these changes

2022-08-02 17:48 UTC, closed without merging