Solution
mate-academy/react_people-table-basics pull request #465
Opened 2023-01-06 11:45 UTC by Ivanenko1402

[DEMO LINK](https://Ivanenko1402.github.io/react_people-table-basics/)

2023-01-06 18:22 UTC, loralevitska requested changes
Almost done)

2023-01-06 18:22 UTC, loralevitska commented on src/components/PeoplePage/PeoplePage.tsx
> +  const [showError, setShowError] = useState<boolean>(false);
```suggestion
  const [isShowError, setIsShowError] = useState<boolean>(false);
```
[Tips on naming boolean variables](https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig)
Fix all cases if present

2023-01-06 18:22 UTC, loralevitska commented on src/components/PeoplePage/PeoplePage.tsx
> +          {people.length > 0 && (
```suggestion
          {Boolean(people.length) && (
```

2023-01-06 18:22 UTC, loralevitska commented on src/components/PersonLink/PersonLink.tsx
> +      </td>
combine it to `parent` variable

2023-01-07 10:15 UTC, Anastasiia-Svintsova requested changes
Good job! Fix some comment please

2023-01-07 10:15 UTC, Anastasiia-Svintsova commented on src/App.tsx
> +} from 'react-router-dom';
```suggestion
import { Outlet } from 'react-router-dom';
```

2023-01-07 10:15 UTC, Anastasiia-Svintsova commented on src/components/PeoplePage/PeoplePage.tsx
> +    getParent();
Why do you need to call the getParent() function here in useEffect? It's useless

2023-01-07 10:15 UTC, Anastasiia-Svintsova commented on src/components/PeoplePage/PeoplePage.tsx
> +  const people = getParent();
Wrap it in `useMemo()`;

2023-01-07 10:15 UTC, Anastasiia-Svintsova commented on src/components/PeopleTable/PeopleTable.tsx
> +          key={`${person.slug}`}
```suggestion
          key={person.slug}
```

2023-01-07 15:07 UTC, Anastasiia-Svintsova approved these changes

2023-01-07 15:07 UTC, Anastasiia-Svintsova commented on src/components/PeoplePage/PeoplePage.tsx
> +  }, [peopleList]);
You need to pass getParent function to the dependency array and wrap it into useCallback. It'll be the correct way to memorize this value.
```suggestion
  const people = useMemo(() => {
    return getParent();
  }, [getParent]);
```

2026-03-02 13:13 UTC, closed without merging