solution
mate-academy/react_people-table-basics pull request #526
Opened 2023-02-02 22:15 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_people-table-basics/)

2023-02-03 12:42 UTC, anastasiia-bilska approved these changes
Well done!

2023-02-03 13:48 UTC, solaryasha requested changes

2023-02-03 13:48 UTC, solaryasha commented on src/components/Loader/pages/CustomNavLink.tsx
> +  to: string;
Let's use `To` interface from `react-router-dom`
```suggestion
  to: To;
```

2023-02-03 13:48 UTC, solaryasha commented on src/components/Loader/pages/PeoplePage.tsx
> +  const loadedPeople = async () => {
The callback should start with the verbs (load, start,add,delete)

2023-02-03 13:48 UTC, solaryasha commented on src/components/Loader/pages/PeoplePage.tsx
> +      const loadPeople = await getPeople();
```suggestion
      const loadedPeople = await getPeople();
```

2023-02-06 18:37 UTC, valerii-derkach approved these changes

2023-02-06 18:37 UTC, valerii-derkach commented on src/components/Loader/pages/PeoplePage.tsx
> +        const fountFather = loadedPeople.find(
```suggestion
        const foundFather = loadedPeople.find(
```

2026-07-13 23:08 UTC, closed without merging