done
mate-academy/react_people-table-basics pull request #553
Opened 2023-02-17 00:27 UTC by panianchuk

https://panianchuk.github.io/react_people-table-basics/#/

2023-02-17 15:46 UTC, slavanosatskyi requested changes
Nice, though I would change a couple of variables names

2023-02-17 15:46 UTC, slavanosatskyi commented on src/components/PeoplePage/PeoplePage.tsx
> +        setIsLoading(false);
you don't need to duplicate it here as long as it is in finally block

2023-02-17 15:46 UTC, slavanosatskyi commented on src/components/PeoplePage/PeoplePage.tsx
> +  const [persons, setPersons] = useState<Person[]>([]);
```suggestion
  const [peolple, setPeolple] = useState<Person[]>([]);
```

2023-02-17 15:46 UTC, slavanosatskyi commented on src/components/PeoplePage/PeoplePage.tsx
> +  const isCountPersonsLoaded = persons.length === 0;
the name gives wrong association. Better to name in a way that shows your intention - isPeopleListEmpty or something

2023-02-18 10:56 UTC, ViktorHavryliuk approved these changes

2023-12-10 20:12 UTC, closed without merging