solution
mate-academy/react_people-table-basics pull request #654
Opened 2023-04-13 14:53 UTC by Nordexz

[DEMO LINK](https://nordexz.github.io/react_people-table-basics/)

2023-04-16 11:18 UTC, mstrilec approved these changes
GJ!

2023-04-18 16:40 UTC, OleksiiBlezniuk requested changes

2023-04-18 16:40 UTC, OleksiiBlezniuk commented on src/components/PeoplePage/PeoplePage.tsx
> +  const { slug = '' } = useParams();
It's better to use a more specific type for the useParams hook. You can define an interface for the expected parameters and pass it to the hook like this: `useParams<YourInterface>();`

2023-04-18 16:40 UTC, OleksiiBlezniuk commented on src/components/PeopleTable/PeopleTable.tsx
> +    ArrayOfPeople: Person[],
Consider renaming the 'ArrayOfPeople' parameter to 'arrayOfPeople' for consistency with camelCase naming conventions 🐫

2023-04-18 16:40 UTC, OleksiiBlezniuk commented on src/components/PeoplePage/PeoplePage.tsx
> +          {people.length
Better to wrap it to boolean or compare with come value, now 0 is rendered  if length is 0
![Screenshot 2023-04-18 at 19 33 31](https://user-images.githubusercontent.com/84275496/232845410-6dd3b54f-2b9a-4619-8d10-028cd5ff27f4.png)

2023-04-18 16:40 UTC, OleksiiBlezniuk commented on src/components/PeopleTable/PeopleTable.tsx
> +  people: Person[]
```suggestion
  people: Person[];
```

2023-04-18 16:40 UTC, OleksiiBlezniuk commented on src/components/PeopleTable/PeopleTable.tsx
> +          const father = findParent(people, fatherName);
Use this functions to prepare array from server, now it will find objects on every render, let's avoid it

2023-04-18 16:40 UTC, OleksiiBlezniuk commented on src/components/PersonLink/PersonLink.tsx
> +  person: Person
```suggestion
  person: Person;
```

2025-09-29 20:21 UTC, closed without merging