New
mate-academy/react_people-table-basics pull request #709
Opened 2023-05-13 11:10 UTC by VadimDrobyazko

[DEMO LINK](https://vadimdrobyazko.github.io/react_people-table-basics/)

Я не понимаю почему не работают ссылки mother, father. Help

2023-05-13 13:33 UTC, VitaliyBondarenko1982 requested changes

2023-05-13 13:33 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +    setIsLoading(true);
```suggestion
    setIsLoading(true);
    
    const fetchPeople = await getPeople();
```
it should fix this test
![Screenshot from 2023-05-13 16-30-49](https://github.com/mate-academy/react_people-table-basics/assets/33029864/180011ba-647f-4f36-9d03-6eded300a9ed)

2023-05-13 13:33 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +      setIsLoading(false);
```suggestion
```
redundant 
finally block will word in any case

2023-05-14 08:59 UTC, etojeDenys requested changes

2023-05-14 08:59 UTC, etojeDenys commented on src/components/PeoplePage/PeoplePage.tsx
> +  error: boolean,
Missing semicolon at the end of the line.

2023-05-14 08:59 UTC, etojeDenys commented on src/components/PeopleTable/PeopleTable.tsx
> +      {people.length < 0 ? (
Replace 'people.length < 0' with 'people.length === 0' to correctly check for an empty array of people.

2023-05-14 08:59 UTC, etojeDenys commented on src/App.tsx
> +    const fetchPeople = await getPeople();
Missing error handling for the API call. Wrap the API call in a try-catch block.

2023-05-14 08:59 UTC, etojeDenys commented on src/App.tsx
> +  const getpeople = async () => {
The function name `getpeople` should be in camelCase as `getPeople`.

2023-05-14 08:59 UTC, etojeDenys commented on src/App.tsx
> +    <>
redundant fragment

2023-05-14 13:24 UTC, VitaliyBondarenko1982 approved these changes

2024-04-14 09:32 UTC, closed without merging