Solution
mate-academy/react_people-table-basics pull request #820
Opened 2023-07-07 13:16 UTC by amashutikov

[DEMO LINK](https://amashutikov.github.io/react_people-table-basics/)

2023-07-11 09:02 UTC, dinaminahi requested changes
Good job! 👍 
But let's do some improvements

2023-07-11 09:02 UTC, dinaminahi commented on src/pages/PepoplePage.tsx
> +            ))}
```suggestion
          !peopleFromServer?.length
            ?  <p data-cy="noPeopleMessage">
                There are no people on the server
              </p>
            : <PeopleTable peopleFromServer={peopleFromServer} />
            }
```

2023-07-11 09:02 UTC, dinaminahi commented on src/components/TablePersonParents.tsx
> +
Soo confusing, create some variables, and check if you need so many react fragments

2023-07-17 07:42 UTC, silchyn requested changes

2023-07-17 07:42 UTC, silchyn commented on src/components/PeopleTable.tsx
> +const tableHeads: string[] = [
```suggestion
const columns: string[] = [
```

2023-07-17 07:42 UTC, silchyn commented on src/components/PeopleTable.tsx
> +  const findParent = useCallback((motherName: string) => {
Is it only mother?

2023-07-17 07:42 UTC, silchyn commented on src/components/PersonLink.tsx
> +  return (
```suggestion
export const PersonLink: React.FC<Props> = ({ person }) => (
```

2023-07-17 07:42 UTC, silchyn commented on src/components/TablePersonParents.tsx
> +        : <td>-</td>}
```suggestion
      <td>
        {personMother
          ? <PersonLink person={personMother} />
          : '-'}
      </td>
```

2023-07-17 07:42 UTC, silchyn commented on src/pages/PepoplePage.tsx
> +  const [isDownloading, setIsDownloading] = useState(false);
What is downloading?

2023-07-17 07:42 UTC, silchyn commented on src/pages/PepoplePage.tsx
> +        }
What's the point?

2023-07-17 07:42 UTC, silchyn commented on src/pages/PepoplePage.tsx
> +          {(isDownloading && !peopleFromServer) && <Loader />}
Put it in a separate variable

2023-11-29 15:48 UTC, closed without merging