Solution
mate-academy/react_people-table-basics pull request #898
Opened 2023-08-04 17:39 UTC by outofs

https://outofs.github.io/react_people-table-basics/

2023-08-05 12:17 UTC, maxyma-sanx approved these changes
Good work

2023-08-06 18:17 UTC, And678 requested changes
Very good, but can be improved

2023-08-06 18:17 UTC, And678 commented on src/components/PeopleTable/PeopleTable.tsx
> +                    ? isLinkedPerson(person.motherName, people)
You are doing this `isLinkedPerson` search twice per every person **per every render**.
Memoize it to prevent extra searching. (useMemo)

2023-08-07 19:08 UTC, And678 approved these changes
GJ, but check my comment

2023-08-07 19:08 UTC, And678 commented on src/components/PeopleRow/PeopleRow.tsx
> +const isLinkedPerson = (name: string, table: Person[]) => {
```suggestion
const findLinkedPerson = (name: string, table: Person[]) => {
```

2023-08-07 19:08 UTC, And678 commented on src/components/PeopleRow/PeopleRow.tsx
> +const isLinkedPerson = (name: string, table: Person[]) => {
This is a func, not a boolean

2025-12-01 12:29 UTC, closed without merging